### PR TITLE
feat(frontend): Added initial frontend scaffolding with a map and searchbar

### PR DESCRIPTION
**Pull request by nicolasperez19**
**What I've done:**
✔ Added a `Map` component from [React Map GL](https://visgl.github.io/react-map-gl/) with basic playwright tests to see if its visible. The map can be zoomed in and can be dragged. I made the component extensible so that in the future it is easy to change the theming for dark/light mode. I also made sure to store the Mapbox API token as an environment variable, so to view the map make sure to add your API token in a `.env` file under `VITE_MAPBOX_API_TOKEN`.
✔ Added a `Searchbar` component using [Material UI](https://mui.com/) with basic playwright tests to see if its visible and that a user can type in the searchbar. It's designed responsibly so it can properly be viewed on both mobile and desktop. I also added a menu button to the side of the searchbar so that it's extensible in the future for adding the data attribution and the ability to toggle the color theme/mode.
✔ Added a `SearchResults` component [Material UI](https://mui.com/) that displays results that match the keyword that a user is searching one. It's designed responsibly so it can properly be viewed on both mobile and desktop.
✔ Added a `Header` component that wraps both the `Searchbar` and `SearchResults` so that it's properly displayed above the `Map` component
✔ Added a `useMapView` [custom React hook](https://react.dev/learn/reusing-logic-with-custom-hooks) so that we can easily manipulate the map

**What still needs to be added/What I plan on adding in the future:**
⚠ I plan on adding the option for dark/light theme. I get a random error with [Material UI](https://mui.com/), so I plan on debugging that in the future.
⚠ I plan on adding the option to query the data from the API. I plan on using [Tanstack Query](https://tanstack.com/query/v3/) instead of fetch because the library easily handles loading and error states. This could be nice for the end user as we could put a loading spinner when the map is still loading the data, etc.
⚠ I plan on adding the heatmap layer on the map. I was going to add it to this pull request, but I wanted to limit the size of this pull request. I was also having errors trying to display the heatmap layer. I followed [this mapbox tutorial](https://docs.mapbox.com/help/tutorials/make-a-heatmap-with-mapbox-gl-js/) and [this react map gl heatmap example](https://visgl.github.io/react-map-gl/examples/heatmap), but I was still having errors for some reason.
⚠ I plan on adding mock data on the frontend just so that it's easy to rapidly prototype. We need to work on an example for a response shape, as that will help avoid a lot of pain developing the frontend.
⚠ I was also planning on adding some documentation to the README from my past sprints as there's a lot of overlap.

### CODE REVIEW

**Comment by nicolasperez19** [comment]
✔ Added mock geojson data with sentiments for a given area
✔ Added heatmap layer to map to display mock geojson data
✔ Added colorblind friendly colors to the heatmap layer

**Comment by nicolasperez19** [comment]
**What I've done**
✔ Added a `DateFilterButton` component in the `Searchbar` so that the end user can filter their search by a given year
✔ Added a `DateFilterDialog` component that appears when `DateFilterButton` is clicked. It has a slider where the end user can select any year within the past 20 years. It defaults to the current year (2023).
✔ Added basic information to the `README`, including:

- Project details
- How to install, run, and test the project

**What still needs to be done:**
⚠ `DateFilterDialog` looks awkward on mobile. I want to make it more responsive
⚠ I still need to sync the state change from the `DateFilterDialog` with the search query

**Comment by nicolasperez19** [comment]
**What I've done**
✔ Added ability for an end user to click on a heatmap point
✔ Added a `HeatmapPopup` component to display information about a heatmap point
✔ Added a `useHeatmapPopup` custom hook to decouple logic from `HeatmapPopup` component

**Review by zaultavangar — APPROVED** [review]
This looks great, thanks so much man. A lot to uncover here so will take a while to really understand everything. But looks like you've added all the basic functionality for the frontend as well as some tests.

**Pull request merged**
